const OPERATION_STATUS = {
    PENDING_FOCUS: 'PENDING_FOCUS',
    PENDING_CAPTURE: 'PENDING_CAPTURE',
    CAPTURED: 'CAPTURED'
};

const FOCUS_SLEEP_MS = 3000;
const CAPTURE_SLEEP_MS = 2000;

module.exports = {
    OPERATION_STATUS,
    FOCUS_SLEEP_MS,
    CAPTURE_SLEEP_MS
};